import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

// Must match the source filenames generated by super-html.
export var PROJECT_NAME = "SpingSpearPLA_x10";
export var VERSION_NAME = "SSP_PA001_GP_Grow_BalloonUpDown_New";
export var BUILD_TARGET = "web-mobile";
export var PROJECT_ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
export var BUILD_ROOT = getBuildRoot();
export var TEMPLATES_ROOT = path.join(PROJECT_ROOT, "build-templates", BUILD_TARGET);

function getBuildRoot(): string {
  if (process.env.BUILD_ROOT) return path.resolve(PROJECT_ROOT, process.env.BUILD_ROOT);
  var profiles = [
    path.join(PROJECT_ROOT, "profiles", "v2", "packages", BUILD_TARGET + ".json"),
    path.join(PROJECT_ROOT, "profiles", "v2", "packages", "builder.json"),
  ];
  for (var i = 0; i < profiles.length; i++) {
    if (!fs.existsSync(profiles[i])) continue;
    var profile = JSON.parse(fs.readFileSync(profiles[i], "utf8"));
    var common = profile.builder ? profile.builder.common : profile.common;
    if (common && typeof common.buildPath === "string" && common.buildPath.trim()) {
      var buildPath = common.buildPath.trim();
      if (buildPath.indexOf("project://") === 0) buildPath = buildPath.slice("project://".length);
      return path.resolve(PROJECT_ROOT, buildPath);
    }
  }
  return path.join(PROJECT_ROOT, "build");
}

